AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  EnforcedStyle: compact

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
    - examples/**/*.rb
